spring:
  application:
    name: shop-turbine
server:
  port: 7777

turbine:
  app-config: shop-stock
  aggregator:
    cluster-config: default
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: actuator/hystrix.stream

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.105:8761/eureka/