server:
  port: 8090

spring:
  rabbitmq:
    host: 120.27.239.4
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0 #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data: #读取不到配置时可以使用此配置，以免项目无法启动
  env: NaN
  user:
    username: NaN
    password: NaN



