server:
  port: 8090

spring:
  rabbitmq:
    host: 120.27.239.4
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

data: #读取不到配置时可以使用此配置，以免项目无法启动
  env: NaN
  user:
    username: NaN
    password: NaN



