server:
  port: 8080

spring:
  application:
    name: shop-stock
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0 #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.105:8761/eureka/
